### ISSUE TITLE
v3.1 breaks `get_citedby()`

### ISSUE THREAD

**Issue by tarensanders** [scholarly-python-package/scholarly#128]
To replicate, just run the example from the readme or docs (suppressed print statements):
```
# Retrieve the author's data, fill-in, and print
search_query = scholarly.search_author('Steven A Cholewiak')
author = next(search_query).fill()
#print(author)

# Print the titles of the author's publications
# print([pub.bib['title'] for pub in author.publications])

# Take a closer look at the first publication
pub = author.publications[0].fill()
# print(pub)

# Which papers cited that publication?
print([citation.bib['title'] for citation in pub.get_citedby()])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-066d73649888> in <module>
     12 
     13 # Which papers cited that publication?
---> 14 print([citation.bib['title'] for citation in pub.get_citedby()])

AttributeError: 'Publication' object has no attribute 'get_citedby'
```

The `citedby` attribute is also broken:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-a53fc3706a52> in <module>
----> 1 pub1.citedby

/opt/anaconda3/lib/python3.7/site-packages/scholarly/publication.py in citedby(self)
    241         if not self.filled:
    242             self.fill()
--> 243         return _SearchScholarIterator(self.nav, self.citations_link)
    244 
    245     @property

AttributeError: 'Publication' object has no attribute 'citations_link'
```

**Comment by silvavn** [comment]
I have just reviewed the code. the fill function gets the citation count but never the link to the citations.
We will address this bug on the next release soon™.

**Comment by silvavn** [comment]
Hi! Please refer to the latest `develop` branch as I have addressed this bug :)
Thanks for reporting, and please let me know if that fixes it.

Notice that now the syntax should be `citedby` to get a list `b` that cites paper `a`.
Also, I have changed the `.bib` to `.bibtex`

```python
from scholarly import scholarly

tor_sock_port = 9150
tor_control_port = 9151
scholarly.use_tor(tor_sock_port, tor_control_port, "")
search_query = scholarly.search_author('Steven A Cholewiak')
author = next(search_query).fill()
print(author)

# Take a closer look at the first publication
pub = author.publications[0].fill()
print(pub)

# Which papers cited that publication?
print([citation.bibtex['title'] for citation in pub.citedby])
```

**Comment by tarensanders** [comment]
Fantastic, it's working great. Actually seems a little faster too. Note that #117 isn't on this branch but that's OK.

Really appreciate your work in this package. The use of Tor is really helpful.

**Comment by yesterday2two** [comment]
I am very sorry but, under the command

print([citation.bibtex['title'] for citation in pub.citedby])

I still get the following error:

AttributeError: 'Publication' object has no attribute 'citations_link'

I am sorry, am i missing something? Thank you.

**Comment by Equationliu** [comment]
> I am very sorry but, under the command
> 
> print([citation.bibtex['title'] for citation in pub.citedby])
> 
> I still get the following error:
> 
> AttributeError: 'Publication' object has no attribute 'citations_link'
> 
> I am sorry, am i missing something? Thank you.

i encountered the same question, is there any solution?

**Comment by AtelierCartographique** [comment]
> Hi! Please refer to the latest `develop` [49f3480](https://github.com/scholarly-python-package/scholarly/commit/49f3480d808a89833fb85782e955b0a029dca0ac) branch as I have addressed this bug :)
> Thanks for reporting, and please let me know if that fixes it.
> 
> Notice that now the syntax should be `citedby` to get a list `b` that cites paper `a`.
> Also, I have changed the `.bib` to `.bibtex`
> 
> ```python
> from scholarly import scholarly
> 
> tor_sock_port = 9150
> tor_control_port = 9151
> scholarly.use_tor(tor_sock_port, tor_control_port, "")
> search_query = scholarly.search_author('Steven A Cholewiak')
> author = next(search_query).fill()
> print(author)
> 
> # Take a closer look at the first publication
> pub = author.publications[0].fill()
> print(pub)
> 
> # Which papers cited that publication?
> print([citation.bibtex['title'] for citation in pub.citedby])
> ```

Thanks! however, how can one specifically install "49f3480" version of Scholarly using pip?

**Comment by Tisi-theeconomist** [comment]
This problem is not solved i still see this same error. 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-65-3e0a54e992a5> in <module>
      2 citation = []
      3 for i in papers_cited:
----> 4     for j in i.citedby:
      5         citation.append(j)
      6         #convert citation into a dataframe

~\Anaconda3\lib\site-packages\scholarly\publication.py in citedby(self)
    279         if not self.filled:
    280             self.fill()
--> 281         return _SearchScholarIterator(self.nav, self.citations_link)
    282 
    283     @property

AttributeError: 'Publication' object has no attribute 'citations_link'

**Comment by ipeirotis** [comment]
Tried executing the code: 

```python
from scholarly import scholarly

search_query = scholarly.search_author('Steven A Cholewiak')
author = next(search_query).fill()
print(author)

# Take a closer look at the first publication
pub = author.publications[0].fill()
print(pub)

# Which papers cited that publication?
print([citation.bibtex['title'] for citation in pub.citedby])
```

with the latest version of scholarly (`v.0.5`), available through pip. 

Runs without a problem. I cannot replicate the issue. Closing this.
