### ISSUE TITLE
citedby function still returns empty results?

### ISSUE THREAD

**Issue by talhakabakus** [scholarly-python-package/scholarly#471]
**Describe the bug**
As the title is self-descriptive, the `citedby` function returns empty results.

**To Reproduce**
```
from scholarly import scholarly, ProxyGenerator

pg = ProxyGenerator()
pg.FreeProxies()
scholarly.use_proxy(pg)

search_query = scholarly.search_author('Abdullah Talha Kabakus')
author = scholarly.fill(next(search_query))

pub = author['publications'][0]
citations = scholarly.citedby(pub)
for citation in list(citations):
    print(citation)
```

**Expected behavior**
The 243 publications that cites the corresponding paper.

**Desktop (please complete the following information):**
 - Proxy service: The built-in proxy service
 - python version: 3.8
 - OS: macOS Ventura 13.1 (Apple Silicon M2 SoC)
 - Version: 1.7.5 (the latest available one in the `conda` repository)

**Comment by arunkannawadi** [comment]
Please try this with v1.7.6 and let me know if the same issue exists.

**Comment by talhakabakus** [comment]
Hi @arunkannawadi,

Thanks for your quick response, much appreciated. As I've stated in my OP, the latest one available in the `conda` repository is v. `1.7.5`.

**Comment by arunkannawadi** [comment]
This is a known issue in `1.7.5` and conda-forge build fails for reasons that I don't understand. In the meantime, if you have an `environment.yaml`, you could update it to install the latest version from `pip` directly. Apologies for the inconvenience.

```
name: <your-env-name>
channels:
  - conda-forge
  - defaults
dependencies:
  - <any-other-packages>
  - pip:
    - git+https://github.com/scholarly-python-package/scholarly.git
```

**Comment by talhakabakus** [comment]
I see, thanks for making it clear, @arunkannawadi. Since I do not have an `environment.yml`, I'll be waiting for the v. `1.7.6` to be provided in `conda-forge`.

**Comment by talhakabakus** [comment]
I've updated `scholarly` to `1.7.6`. Now getting this error: `fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached`. `fake-useragent` is already up-to-date (v. `1.1.1`). FYI @arunkannawadi.

**Comment by arunkannawadi** [comment]
That's discussed extensively in #465 and fix is coming in `v1.7.7` in a couple of hours. FYI, this has nothing to do with `scholarly` itself.

**Comment by arunkannawadi** [comment]
@talhakabakus - the error has been fixed upstream.  You can use the latest version (v1.7.9), now available on `conda-forge` and you should not see this error. Let me know if you still do.

**Comment by talhakabakus** [comment]
Dear @arunkannawadi many thanks for your feedback. But, unfortunately, I still get the same error.

**Comment by talhakabakus** [comment]
After re-initializing my `venv`, the error that occurs during the execution of `citedby` function is now changed to `scholarly._proxy_generator.MaxTriesExceededException: Cannot Fetch from Google Scholar.`. @arunkannawadi

**Comment by arunkannawadi** [comment]
Yes, that's the exception that is raised whenever Google Scholar identifies that this is a request arising from a program, even with proxies. Either skip the proxy altogether, or use a more reliable service like ScraperAPI (they have a free tier, but it is very limited).

**Comment by talhakabakus** [comment]
Not that I was aware of, - _Arun_. Thanks for your recommendation. Will try the latter one. @arunkannawadi
