### ISSUE TITLE
using 'search_pubs()' as stated in the docs raises a StopIteration Error

### ISSUE THREAD

**Issue by elliotchung** [scholarly-python-package/scholarly#541]
**Describe the bug**
using 'search_pubs()' as stated in the docs raises a StopIteration Error
i think another commenter in #517 mentioned a possible [cause of the error](https://github.com/scholarly-python-package/scholarly/issues/517#issuecomment-1945521162):

**To Reproduce**
```
search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
scholarly.pprint(next(search_query))
```
```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
Cell In[15], line 1
----> 1 scholarly.pprint(next(search_query))

File ~\miniconda3\Lib\site-packages\scholarly\publication_parser.py:93, in _SearchScholarIterator.__next__(self)
     91     return self.__next__()
     92 else:
---> 93     raise StopIteration

StopIteration:
```

**Expected behavior**
Returns the single search result of this publication

**Screenshots**

**Desktop (please complete the following information):**
 - Proxy service: NIL
 - python version: 3.11.5
 - OS: Win10
 - Version 1.7.11

**Do you plan on contributing?**
No

**Comment by keko24** [comment]
Hey, I am currently working on a fix, but in the mean time search_single_pub works properly for this case.

**Comment by keko24** [comment]
Hey, this was fixed so it should be closed.

**Comment by gdudek** [comment]
I am still seeing this error with a fresh re-install of scholarly and dependencies.

**Comment by keko24** [comment]
This is because a new release has not been made and distributed, so if you are installing it through pip or conda-forge you are still getting the old version. Maybe @arunkannawadi can check this out. Although in the meantime, you can download the git repo and install the package from there, it should work.

**Comment by karl-chan** [comment]
When will a new release be made with the fix? It's been nearly 2 years since the last release. If this repo is no longer maintained could you please update the readme?
